'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class LinkHubDbEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=LinkHubDbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tbl_Category() As DbSet(Of tbl_Category)
    Public Overridable Property tbl_Url() As DbSet(Of tbl_Url)
    Public Overridable Property tbl_User() As DbSet(Of tbl_User)

End Class
