'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Category
    Public Property CategoryId As Integer
    Public Property CategoryName As String
    Public Property CategoryDesc As String

    Public Overridable Property tbl_Url As ICollection(Of tbl_Url) = New HashSet(Of tbl_Url)

End Class
