'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Url
    Public Property UrlId As Integer
    Public Property UrlTitle As String
    Public Property Url As String
    Public Property UrlDesc As String
    Public Property CategoryId As Nullable(Of Integer)
    Public Property UserId As Nullable(Of Integer)
    Public Property IsApproved As String

    Public Overridable Property tbl_Category As tbl_Category
    Public Overridable Property tbl_User As tbl_User

End Class
